export const securityQuestions = {
  eldestSiblingMiddleName: { id: 1, question: 'Your eldest siblings middle name?', answer: 'John' },
  motherMaidenName: { id: 2, question: "Mother's maiden name?", answer: 'Smith' },
  motherBirthDate: { id: 3, question: "Mother's birth date? (MM/DD/YY)", answer: '01/01/70' },
  fatherBirthDate: { id: 4, question: "Father's birth date? (MM/DD/YY)", answer: '02/02/70' },
  maternalGrandmotherFirstName: { id: 5, question: "Maternal grandmother's first name?", answer: 'Rose' },
  paternalGrandmotherFirstName: { id: 6, question: "Paternal grandmother's first name?", answer: 'Helen' },
  favoritePet: { id: 7, question: 'Name of your favorite pet?', answer: 'Buddy' },
  teenageDentistLastName: {
    id: 8,
    question: "Last name of dentist when you were a teenager? (Do not include 'Dr.')",
    answer: 'Johnson',
  },
  teenageZipCode: { id: 9, question: 'Your ZIP/postal code when you were a teenager?', answer: '90210' },
  firstAdultCompany: { id: 10, question: 'Company you first work for as an adult?', answer: 'Google' },
  favoriteBook: { id: 11, question: 'Your favorite book?', answer: 'The Way of Kings' },
  favoriteMovie: { id: 12, question: 'Your favorite movie?', answer: 'The Fellowship of The Ring' },
  customerOrIdCardNumber: { id: 13, question: 'Number of one of your customer or ID cards?', answer: '1234567890' },
  favoriteHikingPlace: { id: 14, question: "What's your favorite place to go hiking?", answer: 'Yosemite' },
};
